version: "3.8"

services:
  api-runner:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_DSN=${MYSQL_DSN}
      - API_PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  

  volumes:
    mysql-data